library(tidyverse)
library(patchwork)
library(ggrepel)

dat <- read_csv("data/N2O_summary_data_04012026.csv", show_col_types = FALSE)
dir.create("plots/figures", showWarnings = FALSE, recursive = TRUE)

model_labels <- c("Wang" = "Linear model", "Qiu" = "Quadratic model")

# ── Load pre-computed components and national summary ─────────────────────────
# Generated by data_prep.R. Qiu filter already applied (avoided < 0 set to 0).
load("data/avoided_emissions_components.Rdata")

# ============================================================
# FIGURE 1 — DOT PLOTS: national totals, EBK pH model
# ============================================================
# Source: summary_total from avoided_emissions_components.Rdata (via data_prep.R).
# Qiu filter already applied. NReductionOnly duplicated across Avg/Max so it
# appears in both pH target panels.
# Two versions:
#   A. fig1_dotplot_ebk_phtarget.png — facet = EF model, color = pH target
#   B. fig1_dotplot_ebk_efmodel.png  — facet = pH target, color = EF model

dot_base <- bind_rows(
    summary_total |>
      filter(n_scenario %in% c("NActual", "Combined"), ph_target %in% c("Avg", "Max")),
    summary_total |>
      filter(n_scenario == "NReductionOnly") |>
      select(-ph_target) |>
      crossing(ph_target = c("Avg", "Max"))
  ) |>
  filter(ph_model == "EBK") |>
  mutate(
    ef_label = factor(recode(ef_model, !!!model_labels), levels = unname(model_labels)),
    ph_label = factor(ph_target, levels = c("Avg", "Max"),
                      labels = c("Average recommended pH", "Maximum recommended pH")),
    scenario_label = factor(recode(n_scenario,
      NActual        = "pH management\nonly",
      NReductionOnly = "N reduction\nonly",
      Combined       = "Both\ncombined"
    ), levels = c("pH management\nonly", "N reduction\nonly", "Both\ncombined")),
    x_num = as.integer(scenario_label),
    y_val = avoided_mean_kgN / 1e6,
    y_sd  = avoided_sd_kgN  / 1e6
  )

dot_theme <- list(
  theme_bw(),
  theme(
    legend.position       = "bottom",
    plot.caption          = element_text(size = 8, hjust = 0, color = "grey35",
                                         margin = margin(t = 6), lineheight = 1.3),
    plot.caption.position = "plot"
  )
)

shared_caption <- paste0(
  "EBK soil pH model. Quadratic model: counties where liming results in a net increase in N\u2082O ",
  "(avoided emissions < 0) set to zero. Error bars = \u00b11 SD."
)

# Plot A: facet = EF model, color = pH target
ph_colors <- c("Average recommended pH" = "#fec44f", "Maximum recommended pH" = "#7f2704")

fig_dot_phtarget <- ggplot(
    mutate(dot_base, x_nudge = if_else(ph_target == "Avg", -0.12, 0.12)),
    aes(x = x_num + x_nudge, y = y_val, color = ph_label)
  ) +
  geom_errorbar(aes(ymin = y_val - y_sd, ymax = y_val + y_sd),
                width = 0.08, linewidth = 0.7) +
  geom_point(size = 3.5) +
  scale_x_continuous(breaks = 1:3,
                     labels = c("pH management\nonly", "N reduction\nonly", "Both\ncombined"),
                     limits = c(0.5, 3.5)) +
  facet_wrap(~ef_label, ncol = 2) +
  scale_color_manual(name = "pH target", values = ph_colors) +
  labs(x = NULL, y = "Avoided N\u2082O-N (kt)",
       caption = paste0(shared_caption,
         " N reduction only: Avg and Max dots overlap \u2014 ",
         "pH target does not affect this scenario.")) +
  dot_theme

ggsave("plots/figures/fig1_dotplot_ebk_phtarget.png",
       fig_dot_phtarget, width = 8, height = 5, dpi = 300)
message("Saved fig1_dotplot_ebk_phtarget")

# Plot B: facet = pH target, color = EF model
ef_colors <- c("Linear model" = "#d95f0e", "Quadratic model" = "#7f2704")

fig_dot_efmodel <- ggplot(
    mutate(dot_base, x_nudge = if_else(ef_model == "Wang", -0.12, 0.12)),
    aes(x = x_num + x_nudge, y = y_val, color = ef_label)
  ) +
  geom_errorbar(aes(ymin = y_val - y_sd, ymax = y_val + y_sd),
                width = 0.08, linewidth = 0.7) +
  geom_point(size = 3.5) +
  scale_x_continuous(breaks = 1:3,
                     labels = c("pH management\nonly", "N reduction\nonly", "Both\ncombined"),
                     limits = c(0.5, 3.5)) +
  facet_wrap(~ph_label, ncol = 2) +
  scale_color_manual(name = "N\u2082O model", values = ef_colors) +
  labs(x = NULL, y = "Avoided N\u2082O-N (kt)",
       caption = paste0(shared_caption,
         " N reduction only: values are identical across pH panels \u2014 ",
         "pH target does not affect this scenario.")) +
  dot_theme

ggsave("plots/figures/fig1_dotplot_ebk_efmodel.png",
       fig_dot_efmodel, width = 8, height = 5, dpi = 300)
message("Saved fig1_dotplot_ebk_efmodel")

# ============================================================
# FIGURE 2 — STATE STACKED BAR: avoided N2O-N by state and crop
# ============================================================
# EBK pH model, Max pH target, combined scenario.
# States ordered independently within each EF model panel.

# Paul Tol "muted" palette — colorblind-safe
crop_colors <- c(
  "Barley"       = "#88CCEE",
  "Corn"         = "#999933",
  "Cotton"       = "#117733",
  "Durum Wheat"  = "#AA4499",
  "Rice"         = "#882255",
  "Sorghum"      = "#CC6677",
  "Spring Wheat" = "#44AA99",
  "Winter Wheat" = "#332288"
)

state_crop_dat <- components |>
  filter(ph_model == "EBK", ph_target == "Max") |>
  group_by(State, Crop, ef_model) |>
  summarise(combined_kt = sum(combined, na.rm = TRUE) / 1e6, .groups = "drop") |>
  mutate(ef_label = factor(recode(ef_model, !!!model_labels), levels = unname(model_labels)))

state_order_wang <- state_crop_dat |> filter(ef_model == "Wang") |>
  group_by(State) |> summarise(total = sum(combined_kt)) |> arrange(total) |> pull(State)
state_order_qiu  <- state_crop_dat |> filter(ef_model == "Qiu") |>
  group_by(State) |> summarise(total = sum(combined_kt)) |> arrange(total) |> pull(State)

make_state_panel <- function(df, efm, state_order, xlim, show_legend = FALSE) {
  ggplot(
    df |> filter(ef_model == efm) |> mutate(State = factor(State, levels = state_order)),
    aes(y = State, x = combined_kt, fill = Crop)
  ) +
    geom_col() +
    scale_fill_manual(values = crop_colors, name = "Crop") +
    scale_x_continuous(labels = scales::comma, limits = c(0, xlim)) +
    labs(title = as.character(unique(df$ef_label[df$ef_model == efm])),
         x = "Avoided N\u2082O-N (kt)", y = NULL) +
    theme_bw() +
    theme(legend.position = if (show_legend) "right" else "none",
          plot.title = element_text(size = 11))
}

stacked_caption <- theme(plot.caption = element_text(size = 8, hjust = 0, color = "grey35",
                                                      margin = margin(t = 6), lineheight = 1.3))

xlim_state <- state_crop_dat |>
  group_by(ef_model, State) |> summarise(total = sum(combined_kt), .groups = "drop") |>
  pull(total) |> max()

fig_state_crop <- make_state_panel(state_crop_dat, "Wang", state_order_wang, xlim_state) +
  make_state_panel(state_crop_dat, "Qiu", state_order_qiu, xlim_state, show_legend = TRUE) +
  plot_annotation(
    title   = "Avoided N\u2082O by state and crop (Max recommended pH, combined scenario)",
    caption = "EBK soil pH model; Max recommended pH target; combined scenario (pH management + N reduction).\nEach panel ordered by that model\u2019s total avoided emissions.",
    theme   = stacked_caption
  )

ggsave("plots/figures/fig2_state_crop_stacked.png", fig_state_crop,
       width = 12, height = 10, dpi = 300)
message("Saved fig2_state_crop_stacked")

# Top 10 states per model
state_totals <- state_crop_dat |>
  group_by(ef_model, State) |>
  summarise(total = sum(combined_kt), .groups = "drop")

top10_wang <- state_totals |> filter(ef_model == "Wang") |>
  slice_max(total, n = 10) |> arrange(total) |> pull(State)
top10_qiu  <- state_totals |> filter(ef_model == "Qiu")  |>
  slice_max(total, n = 10) |> arrange(total) |> pull(State)

make_top10_panel <- function(df, efm, state_order, xlim, show_legend = FALSE) {
  ggplot(
    df |> filter(ef_model == efm, State %in% state_order) |>
      mutate(State = factor(State, levels = state_order)),
    aes(y = State, x = combined_kt, fill = Crop)
  ) +
    geom_col() +
    scale_fill_manual(values = crop_colors, name = "Crop") +
    scale_x_continuous(labels = scales::comma, limits = c(0, xlim)) +
    labs(title = as.character(unique(df$ef_label[df$ef_model == efm])),
         x = "Avoided N\u2082O-N (kt)", y = NULL) +
    theme_bw() +
    theme(legend.position = if (show_legend) "right" else "none",
          plot.title = element_text(size = 11))
}

xlim_top10 <- state_crop_dat |>
  filter(State %in% c(top10_wang, top10_qiu)) |>
  group_by(ef_model, State) |> summarise(total = sum(combined_kt), .groups = "drop") |>
  pull(total) |> max()

fig_state_crop_top10 <- make_top10_panel(state_crop_dat, "Wang", top10_wang, xlim_top10) +
  make_top10_panel(state_crop_dat, "Qiu", top10_qiu, xlim_top10, show_legend = TRUE) +
  plot_annotation(
    title   = "Top 10 states: avoided N\u2082O by crop (Max recommended pH, combined scenario)",
    caption = "EBK soil pH model; Max recommended pH target; combined scenario (pH management + N reduction).\nTop 10 states ranked and ordered separately within each model panel.",
    theme   = stacked_caption
  )

ggsave("plots/figures/fig2_state_crop_stacked_top10.png", fig_state_crop_top10,
       width = 12, height = 6, dpi = 300)
message("Saved fig2_state_crop_stacked_top10")

# ============================================================
# FIGURES 3 & 4 — BUBBLE PLOTS: pH gap × N input × per-acre avoided
# ============================================================
# Per-acre avoided = county avoided N2O-N (kg) / harvested area (acres)
# EBK pH model, Max pH target, combined scenario.

peracre_dat <- components |>
  filter(ph_model == "EBK") |>
  left_join(
    dat |> distinct(State, County, Crop, Average_Area),
    by = c("State", "County", "Crop")
  ) |>
  filter(!is.na(Average_Area), Average_Area > 0) |>
  mutate(
    pH_only_per_acre  = pH_only  / Average_Area,
    N_only_per_acre   = N_only   / Average_Area,
    combined_per_acre = combined / Average_Area,
    ef_label = factor(recode(ef_model, !!!model_labels), levels = unname(model_labels))
  )

bubble_src <- dat |>
  distinct(State, County, Crop, Average_Area, Actual_N_input,
           Total_N_Actual, Total_N_Reduced, MeanEBK, pH_Max) |>
  filter(!is.na(Actual_N_input), Actual_N_input > 0,
         !is.na(Average_Area), Average_Area > 0) |>
  mutate(
    ph_gap           = pH_Max - MeanEBK,
    n_surplus_per_acre = (Total_N_Actual - Total_N_Reduced) / Average_Area
  )

# Area-weighted crop means
bubble_crop <- peracre_dat |>
  filter(ph_target == "Max") |>
  inner_join(bubble_src |> select(-Average_Area), by = c("State", "County", "Crop")) |>
  group_by(Crop, ef_model, ef_label) |>
  summarise(
    mean_ph_gap            = weighted.mean(ph_gap,             w = Average_Area, na.rm = TRUE),
    mean_n_per_acre        = weighted.mean(Actual_N_input,     w = Average_Area, na.rm = TRUE),
    mean_n_surplus_per_acre = weighted.mean(n_surplus_per_acre, w = Average_Area, na.rm = TRUE),
    mean_avoided_per_acre  = sum(combined_per_acre * Average_Area, na.rm = TRUE) /
                             sum(Average_Area,        na.rm = TRUE),
    .groups = "drop"
  ) |>
  mutate(model_label = factor(
    if_else(ef_model == "Wang", "Linear model (Wang)", "Quadratic model (Qiu)"),
    levels = c("Linear model (Wang)", "Quadratic model (Qiu)")
  ))

# FIGURE 3: size = per-acre avoided, fill = crop, border = EF model
model_borders <- c("Linear model (Wang)" = "grey45", "Quadratic model (Qiu)" = "grey10")

# FIGURE 4: same axes, fill = pH management share
bubble_share <- peracre_dat |>
  filter(ph_target == "Max") |>
  inner_join(bubble_src |> select(State, County, Crop, Actual_N_input, ph_gap, n_surplus_per_acre),
             by = c("State", "County", "Crop")) |>
  group_by(Crop, ef_model, ef_label) |>
  summarise(
    mean_ph_gap             = weighted.mean(ph_gap,              w = Average_Area, na.rm = TRUE),
    mean_n_per_acre         = weighted.mean(Actual_N_input,      w = Average_Area, na.rm = TRUE),
    mean_n_surplus_per_acre = weighted.mean(n_surplus_per_acre,  w = Average_Area, na.rm = TRUE),
    mean_avoided_per_acre   = sum(combined_per_acre * Average_Area, na.rm = TRUE) /
                              sum(Average_Area,        na.rm = TRUE),
    ph_fraction             = sum(pH_only_per_acre  * Average_Area, na.rm = TRUE) /
                            sum(combined_per_acre  * Average_Area, na.rm = TRUE),
    .groups = "drop"
  ) |>
  mutate(pt_size = scales::rescale(sqrt(mean_avoided_per_acre), to = c(3, 18),
                                   from = sqrt(range(mean_avoided_per_acre, na.rm = TRUE))))

# ============================================================
# FIGURES 3 & 4 ALTERNATIVE — N surplus on y-axis
# ============================================================
# Y-axis: N surplus per acre = (Total_N_Actual - Total_N_Reduced) / Average_Area
# All other aesthetics identical to the N application rate versions.

fig_bubble_nsurplus <- ggplot(
    mapping = aes(x = mean_ph_gap, y = mean_n_surplus_per_acre,
                  size = mean_avoided_per_acre, fill = Crop)
  ) +
  geom_point(data = filter(bubble_crop, ef_model == "Wang"),
             aes(color = model_label), shape = 21, alpha = 0.45, stroke = 0.5) +
  geom_point(data = filter(bubble_crop, ef_model == "Qiu"),
             aes(color = model_label), shape = 21, alpha = 0.85, stroke = 0.7) +
  geom_text_repel(data = filter(bubble_crop, ef_model == "Wang"),
                  aes(label = Crop), size = 3.2, fontface = "bold",
                  show.legend = FALSE, segment.color = NA,
                  box.padding = 0.8, point.padding = 1.0, max.overlaps = Inf) +
  scale_size_continuous(name = "Avoided N\u2082O-N\n(kg/acre)",
                        range = c(3, 18), breaks = c(0.1, 0.25, 0.5, 1.0)) +
  scale_fill_manual(values = crop_colors, guide = "none") +
  scale_color_manual(
    name   = "N\u2082O model",
    values = model_borders,
    labels = c("Linear model (Wang)" = "Linear model", "Quadratic model (Qiu)" = "Quadratic model"),
    guide  = guide_legend(override.aes = list(size = 5, shape = 21, fill = "grey80",
                                              alpha = c(0.45, 0.85), stroke = c(0.5, 0.7)))
  ) +
  scale_x_continuous(expand = expansion(mult = 0.15)) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.2)), limits = c(0, NA)) +
  labs(
    x       = "Soil pH gap",
    y       = "N surplus after 50% reduction (kg N/acre)",
    caption = paste0(
      "Each crop shown as two concentric circles: outer (transparent) = Linear model (Wang); inner (opaque) = Quadratic model (Qiu).\n",
      "Position is area-weighted national mean: x-axis = max recommended pH \u2212 current EBK pH; y-axis = N surplus (N actual \u2212 N reduced per acre).\n",
      "Bubble size proportional to area-weighted mean avoided N\u2082O-N per harvested acre.\n",
      "EBK soil pH model; max recommended pH target; combined scenario (pH management + N reduction)."
    )
  ) +
  theme_bw() +
  theme(legend.position       = "right",
        plot.caption          = element_text(size = 8, hjust = 0, color = "grey35",
                                             margin = margin(t = 6), lineheight = 1.3),
        plot.caption.position = "plot")

ggsave("plots/figures/fig3_phgap_nsurplus.png", fig_bubble_nsurplus,
       width = 9, height = 6, dpi = 300)
message("Saved fig3_phgap_nsurplus")

fig_bubble_share_nsurplus <- ggplot(bubble_share,
    aes(x = mean_ph_gap, y = mean_n_surplus_per_acre,
        size = mean_avoided_per_acre, fill = ph_fraction, label = Crop)
  ) +
  geom_point(shape = 21, color = "grey30", stroke = 0.5, alpha = 0.9) +
  geom_text_repel(size = 3.2, fontface = "bold", show.legend = FALSE,
                  segment.color = NA, box.padding = 0.5,
                  point.size = bubble_share$pt_size, max.overlaps = Inf) +
  facet_wrap(~ef_label, ncol = 2) +
  scale_fill_gradient2(low = "#1b7837", mid = "#f7f7f7", high = "#762a83",
                       midpoint = 0.5, limits = c(0, 1),
                       name = "pH management\nshare", labels = scales::percent) +
  scale_size_continuous(name = "Avoided N\u2082O-N\n(kg/acre)",
                        range = c(3, 18), breaks = c(0.1, 0.25, 0.5, 1.0)) +
  scale_x_continuous(expand = expansion(mult = 0.15)) +
  scale_y_continuous(expand = expansion(mult = 0.15)) +
  labs(
    x       = "Soil pH gap",
    y       = "N surplus after 50% reduction (kg N/acre)",
    caption = paste0(
      "Each bubble = one crop. Position is area-weighted national mean: x-axis = max recommended pH \u2212 current EBK pH; y-axis = N surplus (N actual \u2212 N reduced per acre).\n",
      "Bubble size proportional to area-weighted mean avoided N\u2082O-N per harvested acre.\n",
      "Fill color shows the fraction of combined avoided N\u2082O-N attributable to pH management (purple) vs N reduction (green).\n",
      "EBK soil pH model; max recommended pH target; combined scenario (pH management + N reduction)."
    )
  ) +
  theme_bw() +
  theme(legend.position       = "right",
        plot.caption          = element_text(size = 8, hjust = 0, color = "grey35",
                                             margin = margin(t = 6), lineheight = 1.3),
        plot.caption.position = "plot")

ggsave("plots/supporting_figures/fig4_phshare_nsurplus.png", fig_bubble_share_nsurplus,
       width = 11, height = 6, dpi = 300)
message("Saved fig4_phshare_nsurplus (supporting figures)")

# ============================================================
# FIGURE 5 — CUMULATIVE AVOIDED N2O BY COUNTY RANK
# ============================================================
# Counties ranked from highest to lowest avoided N2O (pH management only).
# Cumulative curve shows how quickly total avoided emissions plateau as
# lower-impact counties are added — answering: how many counties capture
# most of the potential benefit?
#
# EBK pH model. Two lines per panel: Avg and Max pH targets.
# Two panels: linear (Wang) and quadratic (Qiu) EF models.
# Qiu: negative avoided values (net N2O increase from liming) set to zero before ranking.

# Sum to county level and pivot to long format so pH-only, combined, and N-only
# scenarios can be ranked and cumulated separately. Qiu filter already applied
# in data_prep.R — no clipping needed here.
# N-only does not vary by pH target so it is computed separately and bound in.
cumulative_dat <- components |>
  filter(ph_model == "EBK") |>
  group_by(State, County, ef_model, ph_target) |>
  summarise(
    pH_only  = sum(pH_only,  na.rm = TRUE) / 1e6,
    combined = sum(combined, na.rm = TRUE) / 1e6,
    .groups = "drop"
  ) |>
  pivot_longer(c(pH_only, combined), names_to = "scenario", values_to = "avoided_ktN") |>
  bind_rows(
    # N-only: independent of pH target; filter to one ph_target to avoid
    # double-counting (N_only is identical across Avg and Max rows)
    components |>
      filter(ph_model == "EBK", ph_target == "Max") |>
      group_by(State, County, ef_model) |>
      summarise(avoided_ktN = sum(N_only, na.rm = TRUE) / 1e6, .groups = "drop") |>
      mutate(ph_target = "N_only", scenario = "N_only")
  ) |>
  # Rank counties independently within each ef_model × ph_target × scenario group
  arrange(ef_model, ph_target, scenario, desc(avoided_ktN)) |>
  group_by(ef_model, ph_target, scenario) |>
  mutate(
    county_rank    = row_number(),
    cumulative_ktN = cumsum(avoided_ktN)
  ) |>
  ungroup() |>
  mutate(
    ef_label = factor(recode(ef_model, !!!model_labels), levels = unname(model_labels)),
    ph_label = factor(ph_target,
                      levels = c("Avg", "Max", "N_only"),
                      labels = c("Average pH", "Maximum pH", "Current pH")),
    scenario_label = factor(scenario,
                            levels = c("pH_only", "combined", "N_only"),
                            labels = c("pH management only", "Combined", "N reduction only"))
  )

# ── Spearman rank correlations ────────────────────────────────────────────────
# Two comparisons, both using Combined scenario, EBK pH model:
#   (1) Avg vs Max pH target — does the choice of target change county priorities?
#   (2) Wang vs Qiu EF model — does model choice change county priorities?

county_combined <- cumulative_dat |>
  filter(scenario == "combined", ph_target %in% c("Avg", "Max"))

# (1) Avg vs Max pH target, within each EF model
cat("\n── Spearman: Avg vs Max pH target (Combined scenario) ──\n")
for (m in c("Wang", "Qiu")) {
  wide <- county_combined |>
    filter(ef_model == m) |>
    select(State, County, ph_target, county_rank) |>
    pivot_wider(names_from = ph_target, values_from = county_rank) |>
    filter(!is.na(Avg), !is.na(Max))
  rho     <- cor(wide$Avg, wide$Max, method = "spearman")
  top_avg <- wide |> slice_min(Avg, n = 100) |> pull(County)
  top_max <- wide |> slice_min(Max, n = 100) |> pull(County)
  overlap <- sum(top_avg %in% top_max)
  cat(sprintf("  %s: rho = %.3f | top-100 overlap = %d/100 (n = %d)\n",
              m, rho, overlap, nrow(wide)))
}

# (2) Wang vs Qiu EF model, Max pH target
cat("\n── Spearman: Wang vs Qiu EF model (Combined, Max pH) ──\n")
wide_models <- county_combined |>
  filter(ph_target == "Max") |>
  select(State, County, ef_model, county_rank) |>
  pivot_wider(names_from = ef_model, values_from = county_rank) |>
  filter(!is.na(Wang), !is.na(Qiu))
rho_models  <- cor(wide_models$Wang, wide_models$Qiu, method = "spearman")
top_wang    <- wide_models |> slice_min(Wang, n = 100) |> pull(County)
top_qiu     <- wide_models |> slice_min(Qiu,  n = 100) |> pull(County)
overlap_mod <- sum(top_wang %in% top_qiu)
cat(sprintf("  Wang vs Qiu: rho = %.3f | top-100 overlap = %d/100 (n = %d)\n",
            rho_models, overlap_mod, nrow(wide_models)))

# Color = pH target; linetype = scenario
cumul_colors    <- c("Average pH" = "#fec44f", "Maximum pH" = "#7f2704",
                     "Current pH" = "grey50")
cumul_linetypes <- c("pH management only" = "dashed", "Combined" = "solid",
                     "N reduction only" = "dotted")

# ── Figure 5: shared absolute threshold version ────────────────────────────────
# Instead of each curve's own 80% threshold, all drop lines point to the same
# absolute y-value: 50% of the best scenario's total (Wang combined Max).
# Curves that never reach the threshold (most pH-only scenarios) have no marker.
# The shared horizontal reference line makes x-positions directly comparable:
# how many counties does each scenario need to hit the same mitigation target?

shared_threshold <- 0.5 * max(
  cumulative_dat |>
    group_by(ef_model, ph_target, scenario) |>
    summarise(total = max(cumulative_ktN), .groups = "drop") |>
    pull(total)
)

threshold_shared <- cumulative_dat |>
  group_by(ef_model, ph_target, scenario, ef_label, ph_label, scenario_label) |>
  filter(max(cumulative_ktN) >= shared_threshold,   # skip curves that never reach it
         cumulative_ktN >= shared_threshold) |>
  slice_min(county_rank) |>
  ungroup()

fig_cumulative_shared <- ggplot(cumulative_dat,
    aes(x = county_rank, y = cumulative_ktN,
        color = ph_label, linetype = scenario_label)
  ) +
  geom_line(linewidth = 0.9) +
  # Horizontal reference line showing the shared target
  geom_hline(yintercept = shared_threshold, linetype = "dotted",
             color = "grey40", linewidth = 0.5) +
  # Vertical drop to x-axis at the shared threshold for each eligible curve
  geom_segment(data = threshold_shared,
               aes(x = county_rank, xend = county_rank,
                   y = 0, yend = shared_threshold),
               linetype = "dotted", linewidth = 0.5, show.legend = FALSE) +
  # Point at the intersection of each curve and the shared threshold
  geom_point(data = threshold_shared,
             aes(y = shared_threshold, shape = "50% of maximum\npotential"),
             size = 1.8, fill = "white", stroke = 1.2) +
  facet_wrap(~ef_label, ncol = 2) +
  scale_color_manual(name = "pH target", values = cumul_colors,
                     guide = guide_legend(override.aes = list(shape = NA))) +
  scale_linetype_manual(name = "Scenario", values = cumul_linetypes) +
  scale_shape_manual(
    name   = NULL,
    values = c("50% of maximum\npotential" = 21),
    guide  = guide_legend(override.aes = list(color = "grey30", fill = "white",
                                              size = 2, stroke = 1.2))
  ) +
  scale_x_continuous(labels = scales::comma,
                     expand = expansion(mult = c(0.01, 0.03))) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +
  labs(
    x       = "Number of counties",
    y       = "Cumulative avoided N\u2082O-N (kt)",
    caption = paste0(
      "EBK soil pH model. Counties ranked independently within each scenario ",
      "by avoided N\u2082O-N, highest to lowest.\n",
      "Combined scenario: liming to recommended pH target + 50% reduction in N surplus. ",
      "N reduction only: 50% reduction in N surplus, no pH change (reference line).\n",
      sprintf("Dotted horizontal line = shared mitigation target (%.1f kt N\u2082O-N; ", shared_threshold),
      "50% of the maximum scenario total). Vertical drop lines show the number of counties ",
      "needed to reach this target; curves that never reach it have no marker.\n",
      "Quadratic model: counties where liming results in a net increase in N\u2082O (avoided emissions < 0) set to zero."
    )
  ) +
  theme_bw() +
  theme(
    legend.position       = "right",
    legend.key.width      = unit(1.2, "cm"),
    plot.caption          = element_text(size = 8, hjust = 0, color = "grey35",
                                         margin = margin(t = 6), lineheight = 1.3),
    plot.caption.position = "plot"
  )

ggsave("plots/figures/fig5_cumulative_county.png", fig_cumulative_shared,
       width = 10, height = 5, dpi = 300)
message("Saved fig5_cumulative_county")

message("\nAll main figures saved to plots/figures/")
