library(tidyverse)
library(flextable)
library(officer)

# ── Load pre-computed national summary ────────────────────────────────────────
# Generated by data_prep.R. Qiu filter already applied (avoided < 0 set to 0).
load("data/avoided_emissions_components.Rdata")

results <- summary_total |>
  mutate(
    ef   = ef_model,
    ph   = ph_model,
    tgt  = ph_target,
    scen = recode(n_scenario,
      NActual        = "pH_only",
      NReductionOnly = "N_only",
      Combined       = "Combined"
    ),
    mean_kt = avoided_mean_kgN / 1e6,
    sd_kt   = avoided_sd_kgN   / 1e6
  )

# ── Shape into table ───────────────────────────────────────────────────────────
row_order <- c("N_only_\u2014", "pH_only_Avg", "pH_only_Max", "Combined_Avg", "Combined_Max")

tbl <- results |>
  filter(!(scen == "N_only" & tgt == "Max")) |>
  mutate(
    tgt_label      = if_else(scen == "N_only", "\u2014", tgt),
    scenario_label = recode(scen,
      N_only   = "N reduction only",
      pH_only  = "pH management only",
      Combined = "Combined"
    ),
    col_key = paste0(ef, "_", ph),
    cell    = sprintf("%.1f \u00b1 %.1f", mean_kt, sd_kt)
  ) |>
  select(scenario_label, tgt_label, col_key, cell) |>
  pivot_wider(names_from = col_key, values_from = cell) |>
  select(scenario_label, tgt_label, Wang_RF, Wang_EBK, Qiu_RF, Qiu_EBK) |>
  mutate(key = paste0(recode(scenario_label,
    "N reduction only"   = "N_only",
    "pH management only" = "pH_only",
    "Combined"           = "Combined"), "_", tgt_label)) |>
  arrange(match(key, row_order)) |>
  select(-key) |>
  # Blank out repeated scenario labels (second row of each two-row block)
  mutate(scenario_label = if_else(tgt_label == "Max", "", scenario_label))

# ── Build flextable ────────────────────────────────────────────────────────────
thick <- fp_border(color = "black", width = 1.5)
thin  <- fp_border(color = "black", width = 0.5)

ft <- tbl |>
  flextable() |>
  set_header_labels(
    scenario_label = "Scenario",
    tgt_label      = "pH target",
    Wang_RF  = "RF",
    Wang_EBK = "EBK",
    Qiu_RF   = "RF",
    Qiu_EBK  = "EBK"
  ) |>
  add_header_row(
    values    = c("", "", "Linear model (Wang)", "Quadratic model (Qiu)"),
    colwidths = c(1, 1, 2, 2)
  ) |>
  # Alignment
  align(align = "left",   j = 1:2, part = "all") |>
  align(align = "center", j = 3:6, part = "all") |>
  # Remove all borders, then add only horizontal lines
  border_remove() |>
  hline_top(   border = thick, part = "header") |>
  hline(i = 1, border = thin,  part = "header") |>   # between the two header rows
  hline_bottom(border = thick, part = "header") |>
  hline(i = 1, border = thin,  part = "body") |>     # after N reduction only
  hline(i = 3, border = thin,  part = "body") |>     # after pH management block
  hline_bottom(border = thick, part = "body") |>
  # Typography
  bold(part = "header") |>
  fontsize(size = 10, part = "all") |>
  font(fontname = "Times New Roman", part = "all") |>
  # Column widths
  width(j = 1, width = 1.6) |>
  width(j = 2, width = 0.8) |>
  width(j = 3:6, width = 1.1) |>
  set_caption(
    caption = paste0(
      "National avoided N\u2082O emissions (kt N\u2082O-N, mean \u00b1 SD) under three management scenarios ",
      "and four model combinations. pH models: RF = random forest, EBK = empirical Bayesian kriging. ",
      "Emission factor models: Linear (Wang et al.) and Quadratic (Qiu et al.). ",
      "For the Quadratic model, county-crop combinations where liming results in a net increase in N\u2082O ",
      "(avoided emissions < 0) are set to zero. SD propagated from county-level spatial uncertainty. ",
      "\u00b9Under the Quadratic model, the polynomial fit peaks at ~pH 5.64: liming within the acidic range ",
      "(where both current and target pH fall below the peak) increases N\u2082O. For the average recommended pH target, 405 county\u2013crop ",
      "combinations across 226 counties exhibit this response, with a total predicted increase of ",
      "0.05 kt N\u2082O-N \u2014 6% of the gross benefit under that scenario. For the maximum recommended pH ",
      "target, 166 county\u2013crop combinations across 111 counties are affected (0.02 kt N\u2082O-N; <1% of ",
      "gross benefit). These values are set to zero in the table."
    )
  )

# ── Export ─────────────────────────────────────────────────────────────────────
doc <- read_docx() |>
  body_add_par("Table 1. National avoided N\u2082O emissions", style = "heading 1") |>
  body_add_flextable(ft)

print(doc, target = "local_only/national_avoided_table.docx")
message("Saved: national_avoided_table.docx")
