library(tidyverse)
library(ggdist)

dir.create("plots/supporting_figures", showWarnings = FALSE, recursive = TRUE)

model_labels <- c("Wang" = "Linear model", "Qiu" = "Quadratic model")

# ── Load pre-computed components ──────────────────────────────────────────────
# Generated by data_prep.R. Qiu filter already applied (avoided < 0 set to 0).
load("data/avoided_emissions_components.Rdata")


# ============================================================
# SUPPORTING FIGURE — Uncertainty decomposition
# ============================================================
# Decomposes variance across 4 model combos (RF/EBK × Linear/Quadratic)
# into EF model, pH model, and interaction contributions per state × crop.

decomp_dat <- components |>
  group_by(State, Crop, ef_model, ph_model, ph_target) |>
  summarise(combined = sum(combined, na.rm = TRUE) / 1e6, .groups = "drop") |>
  pivot_wider(names_from = c(ph_model, ef_model), values_from = combined) |>
  mutate(
    grand_mean  = (RF_Wang + RF_Qiu + EBK_Wang + EBK_Qiu) / 4,
    wang_mean   = (RF_Wang + EBK_Wang) / 2,
    qiu_mean    = (RF_Qiu  + EBK_Qiu)  / 2,
    rf_mean     = (RF_Wang + RF_Qiu)   / 2,
    ebk_mean    = (EBK_Wang + EBK_Qiu) / 2,
    ss_total    = (RF_Wang  - grand_mean)^2 + (RF_Qiu   - grand_mean)^2 +
                  (EBK_Wang - grand_mean)^2 + (EBK_Qiu  - grand_mean)^2,
    ss_ef       = 2 * ((wang_mean - grand_mean)^2 + (qiu_mean  - grand_mean)^2),
    ss_ph       = 2 * ((rf_mean   - grand_mean)^2 + (ebk_mean  - grand_mean)^2),
    ss_interact = ss_total - ss_ef - ss_ph
  ) |>
  filter(ss_total > 1e-10) |>
  transmute(
    State, Crop,
    ph_target = factor(ph_target, levels = c("Avg", "Max"),
                       labels = c("Average recommended pH", "Maximum recommended pH")),
    pct_ef       = 100 * ss_ef       / ss_total,
    pct_ph       = 100 * ss_ph       / ss_total,
    pct_interact = 100 * ss_interact / ss_total
  ) |>
  pivot_longer(c(pct_ef, pct_ph, pct_interact), names_to = "source", values_to = "pct") |>
  mutate(source = factor(recode(source,
    pct_ef       = "EF model\n(Linear vs Quadratic)",
    pct_ph       = "pH model\n(RF vs EBK)",
    pct_interact = "Interaction"
  ), levels = c("EF model\n(Linear vs Quadratic)", "pH model\n(RF vs EBK)", "Interaction")))

decomp_medians <- decomp_dat |>
  group_by(ph_target, source) |>
  summarise(med = median(pct), .groups = "drop")

fig_decomp <- ggplot(decomp_dat, aes(x = source, y = pct, fill = source)) +
  stat_slab(side = "right", width = 0.6, alpha = 0.6, color = NA,
            position = position_nudge(x = 0.1)) +
  geom_boxplot(width = 0.15, outlier.shape = NA, color = "black",
               position = position_nudge(x = -0.05)) +
  geom_text(data = decomp_medians,
            aes(x = source, y = med, label = paste0(round(med, 0), "%")),
            inherit.aes = FALSE, nudge_x = -0.17, size = 3, fontface = "bold") +
  facet_wrap(~ph_target, ncol = 2) +
  scale_fill_manual(values = c(
    "EF model\n(Linear vs Quadratic)" = "#d6604d",
    "pH model\n(RF vs EBK)"           = "#4393c3",
    "Interaction"                      = "#878787"
  ), guide = "none") +
  scale_y_continuous(limits = c(0, 100), labels = \(x) paste0(x, "%")) +
  labs(title    = "Uncertainty decomposition: sources of model variance in avoided N\u2082O",
       subtitle = "% of variance across 4 model combinations (RF/EBK \u00d7 Linear/Quadratic) per state\u00d7crop.\nCombined scenario. Labels show median %.",
       x = NULL, y = "% of total variance") +
  theme_bw() +
  theme(legend.position = "none")

ggsave("plots/supporting_figures/fig_uncertainty_decomp.png", fig_decomp,
       width = 9, height = 6, dpi = 300)
message("Saved fig_uncertainty_decomp")

message("\nAll supporting figures saved to plots/supporting_figures/")
